#!/bin/bash
# Create a GitHub issue for best practices findings
# Usage: ./create-best-practices-issue.sh <findings>

set -euo pipefail

# Get findings from argument or stdin
findings="${1:-$(cat)}"

# Decode the findings (replace %0A with newlines and %% with %)
findings=$(printf '%b' "${findings//\%0A/$'\n'}")
findings="${findings//%%/%}"

# Create the issue body
body="## Best Practices Report

${findings}

Please review and update dependencies as needed.

---
Generated by Best Practices Monitor"

# Create the issue using GitHub CLI
gh issue create \
  --title "chore: external best practices review needed" \
  --body "$body" \
  --assignee dsdeboer \
  --label maintenance \
  --label best-practices
