#!/bin/bash
# Create a GitHub issue for weekly markdown lint fixes
# Usage: ./create-weekly-update-issue.sh

set -euo pipefail

repo_url=$(gh repo view --json url -q .url)
branch_url="${repo_url}/tree/automated/weekly-lint-fixes"

body="## Weekly Markdown Lint Fixes

Automated markdown lint fixes have been applied to the [\`automated/weekly-lint-fixes\`](${branch_url}) branch.

### Actions Required

1. Review the changes in the \`automated/weekly-lint-fixes\` branch
2. Create a pull request manually or merge the changes directly

---
Generated by Weekly Update Check"

gh issue create \
  --title "chore: weekly markdown lint fixes" \
  --body "$body" \
  --assignee dsdeboer \
  --label maintenance
